# Generated by Django 3.1 on 2020-10-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_auto_20201029_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='address',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='position',
            field=models.CharField(choices=[('l1', 'level 1'), ('l2', 'level 2'), ('l3', 'level 3'), ('l4', 'level 4'), ('l5', 'level 5'), ('l6', 'level 6'), ('l7', 'level 7'), ('l8', 'level 8'), ('l9', 'level 9'), ('l10', 'level 10')], default='l1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='salary',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
