# Generated by Django 3.1 on 2020-10-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0006_auto_20201029_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('l1', 'level 1'), ('l2', 'level 2'), ('l3', 'level 3'), ('l4', 'level 4'), ('l5', 'level 5'), ('l6', 'level 6'), ('l7', 'level 7'), ('l8', 'level 8'), ('l9', 'level 9'), ('l10', 'level 10')], max_length=50),
        ),
    ]
